### PR TITLE
add mailcheck to user sign up form

### PR DESCRIPTION
**Pull request by Paul-Hess**

### CODE REVIEW

**Comment by sethherr** [comment]
Hey @Paul-Hess! This is great improvement.

When it's ready to be merged in, add the label `Ready for review` (make sure travis passes first).

**Comment by timlkelly** [comment]
Hi @Paul-Hess would love to merge this in, I can finish this up unless you are looking to do so soon.

**Comment by Paul-Hess** [comment]
Hi @sethherr my apologies for not getting back to this right away. Got busy elsewhere. 
@timlkelly I do hope to be able to ready this after work tonight but if it is more convenient for you to finish it up before then please have at. 
Thanks, hope these changes prove helpful.

**Comment by timlkelly** [comment]
@Paul-Hess sure thing I'll leave it to you then, thanks

**Comment by Paul-Hess** [comment]
@sethherr @timlkelly Hello, I spent a couple hours trying to troubleshoot why this travis build is failing with no success. I don't have previous experience with travis and have not come across a solution in my researching. All tests are passing locally and the ones that fail on the travis build have to do with dates not being parsed correctly in the integration testing environment/I haven't found how they are related to changes that I have made. This is probably due to my inexperience. I would appreciate it if someone else could take a look at it. I am also eager to learn how I could handle this better in the future. 
Thanks.

**Comment by sethherr** [comment]
Hey @Paul-Hess - I'm not sure what happened with the test failure, when it was merged with the current master branch travis passed. Sorry this took a while!

Here are the changes I made in #282 (which extends your branch and is merged now):

- Moved mailcheck.js into [rails-assets](https://rails-assets.org/#/components/mailcheck), because it makes handling dependencies easier.
- rename to UserEmail to CheckEmail, because it's a bit more descriptive
- Instantiate CheckEmail with a target selector so it can be used on more than just the user_email page
- Add a users new coffee file that calls CheckEmail on `#user_email` for signup
- Call CheckEmail for new bikes pages
- Call CheckEmail for the bike edit page that has an email entry
- Call CheckEmail for additional user emails
- Styled the message helper with .form-control-feedback and cursor: pointer

**Pull request closed without merging**
