### PR TITLE
[WIP] Dont buy stolen

### PR DESCRIPTION
**Pull request by ryanhallcs**
code review, not cleaned for merge

bootstrap got included somehow with sidekiq but site uses cdn
generated css is being included in pr, need to remove it - likely need to update .gitignore

### CODE REVIEW

**Comment by sethherr** [comment]
If you give me push access to your repository I can clean this up a bit. Sidekiq and bootstrap are included because I deleted them since you branched off master.

This is great! I've never used data files with jekyll and they're pretty nifty. The data file needs to be converted from json to yaml, because yaml is convention for rails translation files (which's how this will be incorporated it into the main Bike Index app).

**Comment by sethherr** [comment]
... sorry for the gross merge things.

**Comment by ryanhallcs** [comment]
all content and structure is finished. just need to add images and tweak around style to polish

**Comment by sethherr** [comment]
Closing because it's stale

**Pull request closed without merging**
