### PR TITLE
Kill logging in AlertImageUploader

### PR DESCRIPTION
**Pull request by jmromer**
Removes debug logging

### CODE REVIEW

**Comment by sethherr** [comment]
What happened here?

**Comment by jmromer** [comment]
> What happened here?

GitHub automatically closes PRs when its head commit is merged elsewhere.

**Comment by sethherr** [comment]
It seems like the logger statements are still in master? So this should still be open?

**Comment by jmromer** [comment]
> It seems like the logger statements are still in master? So this should still be open?

Yes -- didn't realize it remained closed after I re-pushed.

**Comment by sethherr** [comment]
Force pushes scare me 😉

**Pull request merged**
