### PR TITLE
Translation fixes

### PR DESCRIPTION
**Pull request by sethherr**
- Remove duplicated translation key
- Fix email translation key (so it doesn't show up unescaped, and because it doesn't need to be)

### CODE REVIEW

**Comment by jmromer** [comment]
Does `example` scan in Dutch?

**Comment by jmromer** [comment]
Also, what's the duplicated key removed? I can't tell from the diff. 
I haven't normalized the translation file yet but that's inbound

**Comment by sethherr** [comment]
The entirety of `info: terms_text:` is duplicated.

Touché on the example translation. Switched to `email@gmail.com` which I think is sufficiently universal.

**Comment by jmromer** [comment]
Cool, just checking. 

Re the dupe key -- the changes in en.yml look like they'll be time-consuming to merge. Can we drop those for now? I'm anticipating the normalization script to catch duplicate keys.

**Comment by sethherr** [comment]
I think the diff makes it look worse than it is.

Really, I just deleted line 2190 to 2319 (or 2189-2318, since I deleted the earlier key)

**Comment by jmromer** [comment]
Really not a good use of time. This is what you're looking for:
```
git rebase --onto b574d2ffcae^ b574d2ffcae
```

**Pull request merged**
