### PR TITLE
ISO date standards are cool

### LINKED ISSUE #326: Feature request: use the ISO 8601 date format (YYYY-MM-DD)
Hello bike indexers, 

I'd like to suggest a feature that i think will improve the usability of the project: use the [ISO 8601 date format](https://www.cl.cam.ac.uk/~mgk25/iso-time.html) (YYYY-MM-DD) throughout the site, documentation, etc.
It's an international standard and clearer than the website's current USA-centric formatting of MM.DD.YYYY and MM/DD/YYYY.

### PR DESCRIPTION
**Pull request by realchrisolin**
fresh attempt to implement ISO8601 dates in Bike Index. This will need additional testing to make sure date sorting isn't negatively impacted along with updates for relevant spec tests. Resolves #326

### CODE REVIEW

**Comment by realchrisolin** [comment]
initial attempts to implement this is proving harder than I expected and breaking a bunch of things. In addition to failing spec tests (no surprise there), an `Invalid date` error is thrown when trying to set a registered bike as stolen, yet date format hasn't changed on the bike page (which appears to be generated by `app/views/bikes/show.html.haml`) The related line references a `date_stolen` method in the instance variable `@stolen_record`, yet I can't find where this method is being defined:

```
(personal) [pty1] ~/bike_index (branch:iso8601) » grep -r @stolen_record | grep date_stolen
app/views/admin/stolen_bikes/edit.html.haml:            = @stolen_record.date_stolen.strftime("%m-%d-%Y")
app/views/bikes/pdf.html.haml:                = @stolen_record.date_stolen.strftime("%Y-%m-%d")
app/views/bikes/show.html.haml:          = l @stolen_record.date_stolen, format: :dotted
app/views/bikes/show.html.haml:                = @bike.attr_list_item((l @stolen_record.date_stolen, format: :dotted), "Date #{stolen_type}") # stolen_type defined at start of document
app/views/organizations/embed.html.haml:                = builder.text_field :date_stolen_input, value: @stolen_record.date_stolen.strftime('%Y-%m-%d'), required: true, data: { :'date-format' => 'mm-dd-yyyy' }
```

**Comment by sethherr** [comment]
Merging this into a new branch where I'll do some additional work on it. Thanks for getting the ball rolling @realchrisolin !

**Comment by realchrisolin** [comment]
after looking over the PR you put in, I bit off way more than I can chew here. out of curiosity/education (and if you have the time to explain), why did you/we go with moment?

**Comment by sethherr** [comment]
The PR I’m working on is a significant expansion of the goals, it isn’t just putting things in ISO8601 format. To be clear, just putting things in a more universal format would’ve been great!

I went with moment because it’s  good way of getting the users actual local timezone - automatically.

We’ve needed a better way to track time, since organizations are in different time zones and actually want to be able to see when things happened. Tracking actual time of day when thefts occur also has been a long time coming.

**Comment by realchrisolin** [comment]
IIRC, we ask for the date/time the bike was last seen? For thefts that are caught on video or otherwise happen in a fashion that causes the owner to know the time of day when it occurs, should we have a separate field? Or maybe something like a "I know exactly when my bike was stolen" checkmark that changes the text of the field to reflect the difference between "date/time bike was last seen" and "date/time bike was stolen"?

**Comment by sethherr** [comment]
Good point, we should be consistent and say “when was your bike stolen” everywhere. Obviously people might not know exactly, so I’ll add a help text saying something like “put the closest thing you know in”

**Comment by realchrisolin** [comment]
*that* is something I think I can do!

**Comment by realchrisolin** [comment]
I was wrong. I know how to update the relevant strings, but I'm not sure the best way to put in the help text that'll be both web and mobile friendly.

**Comment by sethherr** [comment]
I just changed the phrasing to say “when bike was stolen”

Let me know if you see something incorrect or if it seems clunky!

**Pull request merged**
