### PR TITLE
revise admin paid feature views

### PR DESCRIPTION
**Pull request by Robertgervais**

### CODE REVIEW

**Comment by Robertgervais** [comment]
paidfeatureindex
paidfeatureedit
paidfeaturenew

**Comment by Robertgervais** [comment]
You know the drill. There's a table here that lives in `admin/organizations/invoices/table` and i'm wondering if you want that edited before this gets merged? i'm planning on hitting that path next anyways.

**Comment by sethherr** [comment]
I think you can wait to edit that table until you revise invoices

**Comment by Robertgervais** [comment]
paidformfixed

**Pull request merged**
